import Link from "next/link";
import { Zap } from "lucide-react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service | Brand Pulse by Coast",
  description: "Terms of Service for Brand Pulse by Coast.",
};

export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-gray-50">
      {/* Header */}
      <header className="border-b border-gray-200 bg-white">
        <div className="mx-auto flex max-w-3xl items-center justify-between px-6 py-4">
          <Link href="/" className="flex items-center gap-2">
            <Zap className="h-5 w-5 text-blue-600" />
            <span className="text-sm font-semibold text-gray-900">
              Brand Pulse
            </span>
            <span className="text-[10px] font-medium text-gray-400">
              by Coast
            </span>
          </Link>
          <Link
            href="/login"
            className="text-sm font-medium text-gray-600 hover:text-gray-900 transition-colors"
          >
            Log in
          </Link>
        </div>
      </header>

      <main className="mx-auto max-w-3xl px-6 py-12">
        <article className="rounded-xl border border-gray-200 bg-white px-8 py-10 shadow-sm">
          <h1 className="text-3xl font-bold text-gray-900">
            Terms of Service
          </h1>
          <p className="mt-2 text-sm text-gray-500">
            Last updated: February 16, 2026
          </p>

          <div className="mt-8 space-y-8 text-sm leading-relaxed text-gray-600">
            <section>
              <h2 className="text-lg font-semibold text-gray-900 mb-3">
                1. Service Description
              </h2>
              <p>
                Brand Pulse is a free service provided by Coast (
                <a
                  href="https://growwithcoast.com"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="text-blue-600 hover:underline"
                >
                  growwithcoast.com
                </a>
                ) that provides AI-powered weekly performance briefs based on
                connected ad account data. The service analyzes your advertising
                metrics and generates insights, recommendations, and action
                items.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 mb-3">
                2. Informational Purposes Only
              </h2>
              <p>
                Brand Pulse provides performance insights for informational
                purposes only. The briefs, recommendations, and action items
                generated by our AI do not constitute financial advice, business
                advice, or professional consulting. You are solely responsible
                for any decisions made based on the content of your briefs.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 mb-3">
                3. User Responsibilities
              </h2>
              <ul className="list-disc ml-5 space-y-2">
                <li>
                  You are responsible for the accuracy of the information you
                  provide during onboarding and in your settings.
                </li>
                <li>
                  You must have proper authorization to connect the ad accounts
                  you link to Brand Pulse.
                </li>
                <li>
                  You agree not to use the service for any unlawful purpose or
                  in violation of any applicable laws or regulations.
                </li>
                <li>
                  You are responsible for maintaining the security of your
                  account credentials.
                </li>
              </ul>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 mb-3">
                4. Data Access
              </h2>
              <p>
                By connecting your Meta ad account, you grant Brand Pulse
                read-only access to your ad performance data. We will never
                modify, create, or delete anything in your ad account. You can
                revoke this access at any time through your Brand Pulse settings
                or through your Meta Business settings.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 mb-3">
                5. Service Availability
              </h2>
              <p>
                Brand Pulse is provided &ldquo;as is&rdquo; and &ldquo;as
                available.&rdquo; We strive to maintain reliable service but do
                not guarantee uninterrupted access. We may update, modify, or
                discontinue features of the service at any time.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 mb-3">
                6. Limitation of Liability
              </h2>
              <p>
                Coast and Brand Pulse shall not be liable for any indirect,
                incidental, special, consequential, or punitive damages arising
                from your use of the service or any decisions made based on the
                content of your briefs. Our total liability for any claims
                arising from the service shall not exceed the amount you have
                paid for the service (which is $0 for the free tier).
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 mb-3">
                7. Account Termination
              </h2>
              <p>
                You may terminate your account at any time by deleting it from
                your Settings page. We reserve the right to suspend or terminate
                accounts that violate these terms. Upon termination, all your
                data will be permanently deleted.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 mb-3">
                8. Changes to Terms
              </h2>
              <p>
                We may update these Terms of Service at any time. Continued use
                of Brand Pulse after changes are posted constitutes acceptance
                of the updated terms. We will make reasonable efforts to notify
                users of significant changes.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 mb-3">
                9. Governing Law
              </h2>
              <p>
                These terms shall be governed by and construed in accordance
                with the laws of the State of Delaware, without regard to its
                conflict of law provisions.
              </p>
            </section>

            <section>
              <h2 className="text-lg font-semibold text-gray-900 mb-3">
                10. Contact
              </h2>
              <p>
                For questions about these terms, contact us at{" "}
                <a
                  href="mailto:pulse@growwithcoast.com"
                  className="text-blue-600 hover:underline"
                >
                  pulse@growwithcoast.com
                </a>
                .
              </p>
            </section>
          </div>
        </article>

        <div className="mt-8 text-center text-xs text-gray-400">
          &copy; {new Date().getFullYear()} Coast. All rights reserved.
        </div>
      </main>
    </div>
  );
}
